### ISSUE TITLE
Coinomi on Android fails to scan the QR code

### ISSUE THREAD

**Issue by EchterAgo** [monsterbitar/SPOS4BCH#1]
Getting the attached message.

![screenshot_20171213-110136](https://user-images.githubusercontent.com/922233/33921355-d6c1c290-dff5-11e7-84af-b1e73b6df0f5.png)

**Comment by EchterAgo** [comment]
Sadly no further details are given why it fails to scan. I also tried with Jaxx, it scanned the address but did not fill in the amount automatically.

**Comment by monsterbitar** [comment]
Coinomi works if you have bitcoin: rather than bitcoincash: at the start, and then offers the user to choose an appropiate currency.

Jaxx being unable to decode the &amount=x part is a missing feature that would probably be good to request from them as it is trivial to implement.

**Comment by monsterbitar** [comment]
To contact coinomi to request addition of the bitcoincash: intent signal, here's a support address:

https://coinomi.freshdesk.com/support/home

**Comment by EchterAgo** [comment]
Will be contacting them. Thanks!
