### ISSUE TITLE
Replace by fee warning?

### ISSUE THREAD

**Issue by proehlen** [monsterbitar/SPOS4BCH#13]
I thought RBF had been removed in Bitcoin Cash but I'm seeing this warning:

![image](https://user-images.githubusercontent.com/8384068/34336582-ececb5c2-e98a-11e7-9905-3e7367e4332e.png)

**Comment by monsterbitar** [comment]
Interesting. The project is forked from a BTC only project and they have support for RBF, so the code is there to detect it. I'm not sure how that code would trigger given that BCH does not have such features.

The transaction went through though. I'll take a look at the code for this when I get some time for it.

**Comment by monsterbitar** [comment]
this project is no longer maintained.
