### ISSUE TITLE
Use xpub key to generate receiving addresses

### ISSUE THREAD

**Issue by acidsploit** [monsterbitar/SPOS4BCH#14]
Hi,

Would you consider using xpub keys to generate unique receiving addresses for each payment? 

More info:
https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki
https://www.yours.org/content/generate-bitcoin-cash-receiving-addresses-from-an-electron-cash-xpub-k-4f2b10fff9d8/

**Comment by monsterbitar** [comment]
I'm sorry for the very late reply.

I would love to have support for dynamic generation of new unique public addresses that correspond to the same private key that the POS has never and will never see.

My problem is that I am I am not that math-savvy and by reading the bip I can sadly state that I will not be able to do this by myself. If this is a part of the bitcoincash.js library (or another easily accessible library from a reputable source), I would love some references.

**Comment by monsterbitar** [comment]
this project is no longer maintained.
