### ISSUE TITLE
add screenshot

### ISSUE THREAD

**Issue by johndpope** [monsterbitar/SPOS4BCH#3]
![snapshot](https://user-images.githubusercontent.com/289994/33945783-fbc742b6-dfed-11e7-8efd-94850fdf130d.png)

![screen shot 2017-12-13 at 10 13 01 am](https://user-images.githubusercontent.com/289994/33945904-46d45a82-dfee-11e7-91f0-770d1b4be231.png)

**Comment by monsterbitar** [comment]
addings screenshots is a good idea.

The current choice of screenshots and their layout consumes alot of vertical space, if it's ok I can take two screenshots and get them side-by-side instead, and move them to after the description.

How do I upload files to github user files for referencing like you have done?

**Comment by johndpope** [comment]
just drag and drop it into this comment webpage - it will auto upload. you can then grab the link.

**Comment by johndpope** [comment]
![screen shot 2017-12-12 at 11 06 30 am](https://user-images.githubusercontent.com/289994/33948843-f5fa60cc-dff5-11e7-9d37-70be612d84ad.png)

**Comment by johndpope** [comment]
<img width="899" alt="screen shot 2017-12-13 at 11 08 23 am" src="https://user-images.githubusercontent.com/289994/33948853-fd0b3210-dff5-11e7-8f92-88445cb75bd3.png">

**Comment by monsterbitar** [comment]
![simplepos4bch](https://user-images.githubusercontent.com/8721695/33949010-9c5b9b52-e028-11e7-8d99-7aac6fdca0fc.png)

**Comment by monsterbitar** [comment]
That one might look good, could you place it below the description text and if it you agree it's time to merge?

**Comment by johndpope** [comment]
sure

**Comment by monsterbitar** [comment]
Thanks for the help, screenshots are now live.
