### ISSUE TITLE
enhancement - add github link to live demo https://payment.monsterbitar.se/

### ISSUE THREAD

**Issue by johndpope** [monsterbitar/SPOS4BCH#6]

**Comment by johndpope** [comment]
that way - can point users to this site instead.

**Comment by johndpope** [comment]
https://twitter.com/johndpope/status/940963557637787649

**Comment by monsterbitar** [comment]
A backlink to this github project page should be added as part of a small footer with copyright information as well. Thanks for pointing it out, I'll get it done soon enough (tm)

**Comment by johndpope** [comment]
fyi - https://github.com/Olsm/cryptowoo-bitcoin-cash-addon

**Comment by monsterbitar** [comment]
Added a link to the github project page and one to the GPLv3 license page.
